apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rnuw71c8b-go
  janus-idp.io/tekton: rnuw71c8b-go
  backstage.io/kubernetes-id: rnuw71c8b-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: rnuw71c8b-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
